# Generated by Django 5.0.3 on 2024-03-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0004_alter_chatmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
    ]
